###################  项目启动配置  ###################
server:
  port: 18080
  context-path: /eplus
  tomcat.uri-encoding: UTF-8

logging:
  file: eplus.log
  path: logs/
  level:
    root: warn
    cn.elwy.eplus: debug
    org.ehcache: error
    org.springframework: error
    com.ulisesbocchio: error
    

log:
  home: ./logs
  level: warn
  charset: UTF-8

###################  eplus配置  ###################
eplus:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  http:
    encoding.force: true
    encoding.charset: UTF-8
    encoding.enabled: true
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  cache:
    type: jcache  
    jcache:
      config: classpath:ehcache3.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider
    
  mvc:
    static-path-pattern: /**
    view:
      prefix: /templates/
      suffix: .htm
  freemarker:
    template-loader-path: classpath:/templates/freemarker/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .htm
    settings:
      template_exception_handler: ignore

  redis:
    host: localhost
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    # Redis数据库索引（默认为0）
    database: 0
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
    ssl: false
    cacheNames: myRedis,j2CacheRedis


shiro:  
  hashAlgorithm: SHA-256
  hashIterations: 1024
  storedCredentialsHexEncoded: true
  loginUrl: /login
  successUrl: /
  unauthorizedUrl: /403
  cacheConfig: classpath:ehcache2.xml
  filterChainDefinitionMap:
    /logout: logout
    /login: anon
    /error: anon
    /static/**: anon
    /resource/**: anon
    /plugins/**: anon
    /pages/**: anon
    /dist/**: anon
    /bootstrap/**: anon
    /reg: anon
    /: authc
#    /**: anon
    /**: authc









    
    
    
    
    
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**



###################  mybatis配置  ###################
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.elwy.eplus.*.entity
  configLocation: classpath:mybatis-config.xml
#mybatis.type-handlers-package: 扫描typeHandlers的包
#mybatis.check-config-location: 检查配置文件是否存在
#mybatis.executor-type: 设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE

#pagehelper分页插件配置
#pagehelper.helperDialect: mysql
#pagehelper.reasonable: true
#pagehelper.supportMethodsArguments: true
#pagehelper.params: count: countSql

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用



druid:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cn_elwy_eplus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  username: root
  password: dbpwd123
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true


---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cn_elwy_eplus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: dbpwd123
    name: cn_elwy_eplus
#    db-name: cn_elwy_eplus
#    filters: log4j,wall,mergeStat
    filters: stat
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒 
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小 
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20




# Druid监控
    druid:
      username: admin
      password: admin
      allow: 
      deny: 
      logSlowSql: true
# Druid stat filter config
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    web-stat-filter.enabled: true
    web-stat-filter.url-pattern: /*
#    web-stat-filter.exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
    web-stat-filter.session-stat-enable: true
    web-stat-filter.session-stat-max-count: 10
    web-stat-filter.principal-session-name: user
#    web-stat-filter.principal-cookie-name: 
    web-stat-filter.profile-enable: true
    filter.stat.db-type: mysql
    filter.stat.log-slow-sql: true
    filter.stat.slow-sql-millis: 1000
    filter.stat.merge-sql: true
    filter.wall.enabled: true
    filter.wall.config.delete-allow: true
    filter.wall.config.drop-table-allow: false
    filter.slf4j.enabled: true
# Druid manage page config
    stat-view-servlet.enabled: true
    stat-view-servlet.url-pattern: /druid/*
    stat-view-servlet.reset-enable: true
    stat-view-servlet.login-username: admin
    stat-view-servlet.login-password: admin
#    stat-view-servlet.allow: 
#    stat-view-servlet.deny: 
    use-global-data-source-stat: true










#多数据源(flowabe的和业务的)
eplus:
  flowable:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cn_elwy_eplus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: dbpwd123
  muti-datasource:
    default-dataSource-name: dataSourceEplus #默认的数据源名称
    url: jdbc:mysql://127.0.0.1:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: dbpwd123

